# Generated by Django 5.2 on 2026-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='filial_name',
            field=models.CharField(max_length=100, verbose_name='Filial'),
        ),
    ]
