# Generated by Django 5.2 on 2026-02-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Umumiy summa'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='summary',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Jami summa'),
        ),
    ]
